### ISSUE TITLE
Unable to use the unavailablePeriods

### ISSUE THREAD

**Issue by scshivam** [PINPODEV/time-slots-finder#267]
This code breaks

```
let TimeSlotsFinder=require("time-slots-finder");

const slots = TimeSlotsFinder.getAvailableTimeSlotsInCalendar({
    calendarData: "",
    calendarFormat: TimeSlotsFinder.TimeSlotsFinderCalendarFormat.iCal,
    configuration: {
        timeSlotDuration: 60,
        minAvailableTimeBeforeSlot: 15,
        minTimeBeforeFirstSlot: 24 * 60, // 48 hours in minutes
        availablePeriods: [{
            isoWeekDay: 5,
            shifts: [{ startTime: "10:00", endTime: "12:30" }] 
        }, {
            isoWeekDay: 6,
            shifts: [
                { startTime: "10:00", endTime: "20:00" },
                { startTime: "10:00", endTime: "13:00" },
            ]
        }],
        unavailablePeriods: [{
            startAt: {year: 2021, month: 09, day: 17, hour: 11, minute: 0},
            endAt: {year: 2021, month: 09, day: 17, hour: 12, minute: 0},
        }],
        timeZone: "Asia/Kolkata",   
    },
    from: new Date("2021-09-12T00:00:00.000+05:30"),
    to: new Date("2021-10-13T23:59:59.999+05:30"),
});
console.log(slots);
```

Error:

TimeSlotsFinderError: Unavailable period nº1 is invalid
    at new TimeSlotsFinderError (/home/runner/TimelySereneIde/node_modules/time-slots-finder/lib/errors.js:22:28)
    at Object.isConfigurationValid (/home/runner/TimelySereneIde/node_modules/time-slots-finder/lib/config-management.js:53:23)
    at _checkSearchParameters (/home/runner/TimelySereneIde/node_modules/time-slots-finder/lib/time-slots.js:84:25)
    at Object.getAvailableTimeSlotsInCalendar (/home/runner/TimelySereneIde/node_modules/time-slots-finder/lib/time-slots.js:38:22)
    at /home/runner/TimelySereneIde/index.js:3:31
    at Script.runInContext (vm.js:130:18)
    at Object.<anonymous> (/run_dir/interp.js:209:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)

**Comment by percypyan** [comment]
Hi @scshivam! Thank you for your report.
I just test your code and I didn't get the error, can you tell me the module's version used?

**Comment by scshivam** [comment]
I am using the below version:

```
"dependencies": {
    "moment": "^2.29.1",
    "time-slots-finder": "^0.5.2"
  }
```

node version: v12.16.1

**Comment by percypyan** [comment]
Can you send me the repository you're using to test this code?
I've used node v12.16.1 and time-slots-finder v0.5.2 and the code didn't break.

**Comment by scshivam** [comment]
[https://replit.com/@shivamchaurasi3/TimelySereneIde#index.js](https://replit.com/@shivamchaurasi3/TimelySereneIde#index.js)

Please use the above link

**Comment by percypyan** [comment]
I'm sorry but even if you're code on replete.com is indeed failing, I haven't any way of debug it. A copy-paste in my local environment, ran with 12.16.1 and time-slots-finder v0.5.2, run properly.
I seams that this bug is in relation with the runtime environment.

Can you open a PR with a failing unit test?

**Comment by scshivam** [comment]
I tried on my local environment. It is working fine except for the unavailable periods.

Below is my code:

```
       let TimeSlotsFinder=require("time-slots-finder");
        const slots = TimeSlotsFinder.getAvailableTimeSlotsInCalendar({
            configuration: {
                timeSlotDuration: 60,
                minAvailableTimeBeforeSlot: 15,
                minTimeBeforeFirstSlot: 24 * 60,
                availablePeriods: [{
                    isoWeekDay: 5,
                    shifts: [{ startTime: "10:00", endTime: "12:30" }]
                }, {
                    isoWeekDay: 6,
                    shifts: [
                        { startTime: "10:00", endTime: "12:30" },
                        { startTime: "13:30", endTime: "17:00" },
                    ]
                }],
                unavailablePeriods: [{
                    startAt: {month: 9, day: 17, hour:5, minute:45},
                    endAt: {month: 9, day: 17, hour:7, minute:30},
                }],
                timeZone: "Asia/Kolkata",
            },
            from: new Date("2021-09-17T00:00:00.000+05:30"),
            to: new Date("2021-09-23T23:59:59.999+05:30"),
        });
        console.log(slots);
```

Also, I tried the below snippet:

```
       let TimeSlotsFinder=require("time-slots-finder");

        const slots = TimeSlotsFinder.getAvailableTimeSlotsInCalendar({
            configuration: {
                timeSlotDuration: 60,
                minAvailableTimeBeforeSlot: 15,
                minTimeBeforeFirstSlot: 24 * 60,
                availablePeriods: [{
                    isoWeekDay: 5,
                    shifts: [{ startTime: "10:00", endTime: "12:30" }]
                }, {
                    isoWeekDay: 6,
                    shifts: [
                        { startTime: "10:00", endTime: "12:30" },
                        { startTime: "13:30", endTime: "17:00" },
                    ]
                }],
                unavailablePeriods: [{
                    startAt: {month: 9, day: 17, hour:11, minute:0},
                    endAt: {month: 9, day: 17, hour:12, minute:0},
                }],
                timeZone: "Asia/Kolkata",
            },
            from: new Date("2021-09-17T00:00:00.000+05:30"),
            to: new Date("2021-09-23T23:59:59.999+05:30"),
        });
        console.log(slots);
```

I am getting the below result:

```
[
  {
    startAt: 2021-09-17T04:30:00.000Z,
    endAt: 2021-09-17T05:30:00.000Z,
    duration: 60
  },
  {
    startAt: 2021-09-17T05:45:00.000Z,
    endAt: 2021-09-17T06:45:00.000Z,
    duration: 60
  },
  {
    startAt: 2021-09-18T04:30:00.000Z,
    endAt: 2021-09-18T05:30:00.000Z,
    duration: 60
  },
  {
    startAt: 2021-09-18T05:45:00.000Z,
    endAt: 2021-09-18T06:45:00.000Z,
    duration: 60
  },
  {
    startAt: 2021-09-18T08:00:00.000Z,
    endAt: 2021-09-18T09:00:00.000Z,
    duration: 60
  },
  {
    startAt: 2021-09-18T09:15:00.000Z,
    endAt: 2021-09-18T10:15:00.000Z,
    duration: 60
  },
  {
    startAt: 2021-09-18T10:30:00.000Z,
    endAt: 2021-09-18T11:30:00.000Z,
    duration: 60
  }
]
```

This should not have as person is unavailable during this time period:
```
  {
    startAt: 2021-09-17T05:45:00.000Z,
    endAt: 2021-09-17T06:45:00.000Z,
    duration: 60
  }
```

**Comment by percypyan** [comment]
@scshivam the second snippet work as expected: `{ month: 9, ... }` in the config means October (since month are 0-indexed here), but your search take place in September, so there isn't any unavailable period during this search period.
I know this can be confusing, but it's the way day.js and moment.js are working, so to simplify things like`{ startAt: myMoment.toObject(), endAt: myMoment2.toObject() }` we chosen to stick with the 0-indexed months.

You can look at the [Readme - Configuration options](https://github.com/PINPODEV/time-slots-finder/blob/main/README.md#configuration-options) for more details about configuration.

Concerning you failing snippet, I still can't reproduce the bug elsewhere that on replit.com only in Run mode (Debugger mode works fine). So please open a PR with a failing unit test. That way we will be able to fix a possible bug.

**Comment by scshivam** [comment]
I am not able to reproduce it as repl.it is an online compiler. But this does not happen in my local system.

**Comment by scshivam** [comment]
Thanks, it works perfectly fine. I am closing the issue. If I am able to reproduce it, I will raise a PR
